name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-latest is for arm64 build, macos-13 is for x86_64
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Set PyInstaller Environment Variable
        run: echo "PYINSTALLER_COMPILE_BOOTLOADER=1" >> $env:GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Set up Python
        run: uv venv --python 3.12 --python-preference only-system

      - name: Install the project
        run: uv sync

      - name: generate requirements.txt
        run: uv pip freeze > requirements.txt

      - run: pip install -r requirements.txt

      - run: pip uninstall pyinstaller && set PYINSTALLER_COMPILE_BOOTLOADER=1 && pip install https://github.com/rokm/pyinstaller/archive/refs/heads/stress-testing.zip
        env:
          PYINSTALLER_COMPILE_BOOTLOADER: 1

      # Compress MacOS app param ignored on Windows
      - run: sh ./app/desktop/build_desktop_app.sh --compress-mac-app
        env:
          PYINSTALLER_COMPILE_BOOTLOADER: 1
      - uses: actions/upload-artifact@v4
        with:
          name: kiln-desktop-${{ runner.os }}-${{ runner.arch }}
          path: ./app/desktop/build/dist/*
